#!/usr/bin/env zsh
source ./SPELL
BUILD_DIR="/tmp/build_netcat"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
echo "Fetching netcat..."
curl -LO "https://github.com/diegocr/netcat/archive/refs/tags/netcat-0.7.1.tar.gz"
echo "Extracting..."
tar -xf *.tar.* || exit 1
cd netcat-0.7.1* || exit 1
./configure --prefix=$PREFIX
make -j$(nproc)
sudo make install
