#!/usr/bin/env zsh
PACKAGE="$1"
if [[ -z "$PACKAGE" ]]; then
  echo "Error: No package name provided to dispel." >&2
  exit 1
fi

if command -v screen >/dev/null; then
  screen -dmS dispel_$PACKAGE zsh -c "./dispel_internal $PACKAGE"
else
  ./dispel_internal "$PACKAGE"
fi
