#!/usr/bin/env zsh
if [[ -z "$1" ]]; then
  echo "Installed packages:"
  ls var/installed | sed 's/.manifest$//'
else
  MANIFEST="var/installed/$1.manifest"
  if [[ ! -f "$MANIFEST" ]]; then
    echo "Error: No manifest found for $1" >&2
    exit 1
  fi
  cat "$MANIFEST"
fi
