#!/usr/bin/env zsh
source ./SPELL
BUILD_DIR="/tmp/build_wireshark"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
echo "Fetching wireshark..."
curl -LO "https://2.na.dl.wireshark.org/src/wireshark-4.7.0.tar.xz"
echo "Extracting..."
tar -xf *.tar.* || exit 1
cd wireshark-4.7.0* || exit 1
./configure --prefix=$PREFIX
make -j$(nproc)
sudo make install
