#!/usr/bin/env zsh
source ./SPELL
BUILD_DIR="/tmp/build_openssh"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
echo "Fetching openssh..."
curl -LO "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.7p1.tar.gz"
echo "Extracting..."
tar -xf *.tar.* || exit 1
cd openssh-9.7p1* || exit 1
./configure --prefix=$PREFIX
make -j$(nproc)
sudo make install
