#!/usr/bin/env zsh
source ./SPELL
BUILD_DIR="/tmp/build_ati-driver"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
echo "Fetching ati-driver..."
curl -LO "https://drivers.amd.com/drivers/linux/amdgpu-pro-23.30-1686898-$(lsb_release -is)-$(lsb_release -rs).tar.xz"
echo "Extracting..."
tar -xf *.tar.* || exit 1
cd ati-driver-23.30* || exit 1
./configure --prefix=$PREFIX
make -j$(nproc)
sudo make install
