#!/usr/bin/env zsh
source ./SPELL
BUILD_DIR="/tmp/build_nvidia-driver"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
echo "Fetching nvidia-driver..."
curl -LO "https://us.download.nvidia.com/XFree86/Linux-x86_64/535.86.10/NVIDIA-Linux-x86_64-535.86.10.run"
echo "Extracting..."
tar -xf *.tar.* || exit 1
cd nvidia-driver-535.86.10* || exit 1
./configure --prefix=$PREFIX
make -j$(nproc)
sudo make install
