#!/usr/bin/env zsh
source ./SPELL
BUILD_DIR="/tmp/build_tmux"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
echo "Fetching tmux..."
curl -LO "https://github.com/tmux/tmux/releases/download/3.4/tmux-3.4.tar.gz"
echo "Extracting..."
tar -xf *.tar.* || exit 1
cd tmux-3.4* || exit 1
./configure --prefix=$PREFIX
make -j$(nproc)
sudo make install
